version: '3.8'

# Custom top-level network
networks:
  neo4j-internal:

services:

  server1:
    # Docker image to be used
    image: neo4j:5-enterprise
    # Hostname
    hostname: server1

    # Service-level network, which specifies the networks, from the list of the top-level networks (in this case only neo4j-internal), that the server will connect to.
    # Adds a network alias (used in neo4j.conf when configuring the discovery members)
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network

    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"

    # Uncomment the volumes to be mounted to make them accessible from outside the container.
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf # This is the main configuration file.
      - ./data/server1:/var/lib/neo4j/data
      - ./logs/server1:/var/lib/neo4j/logs
      - ./conf/server1:/var/lib/neo4j/conf
      - ./import/server1:/var/lib/neo4j/import
      #- ./metrics/server1:/var/lib/neo4j/metrics
      #- ./licenses/server1:/var/lib/neo4j/licenses
      #- ./ssl/server1:/var/lib/neo4j/ssl

    # Passes the following environment variables to the container
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/fedeymanu
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=PRIMARY
      # memory transaction total max
      - NEO4J_dbms.memory.transaction.total.max=3G

    # Simple check testing whether the port 7474 is opened.
    # If so, the instance running inside the container is considered as "healthy".
    # This status can be checked using the "docker ps" command.
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]

    # Set up the user
    user: ${USER_ID}:${GROUP_ID}

  server2:
    image: neo4j:5-enterprise    
    hostname: server2
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./data/server2:/var/lib/neo4j/data
      - ./logs/server2:/var/lib/neo4j/logs
      - ./conf/server2:/var/lib/neo4j/conf
      - ./import/server2:/var/lib/neo4j/import
      #- ./metrics/server2:/var/lib/neo4j/metrics
      #- ./licenses/server2:/var/lib/neo4j/licensesc
      #- ./ssl/server2:/var/lib/neo4j/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/fedeymanu
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms.memory.transaction.total.max=3G
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}

  server3:
    image: neo4j:5-enterprise    
    hostname: server3
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./data/server3:/var/lib/neo4j/data
      - ./logs/server3:/var/lib/neo4j/logs
      - ./conf/server3:/var/lib/neo4j/conf
      - ./import/server3:/var/lib/neo4j/import
      #- ./metrics/server3:/var/lib/neo4j/metrics
      #- ./licenses/server3:/var/lib/neo4j/licenses
      #- ./ssl/server3:/var/lib/neo4j/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/fedeymanu
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms.memory.transaction.total.max=3G
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}

  server4:
    image: neo4j:5-enterprise    
    hostname: server4
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7477:7474"
      - "7690:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./data/server4:/var/lib/neo4j/data
      - ./logs/server4:/var/lib/neo4j/logs
      - ./conf/server4:/var/lib/neo4j/conf
      - ./import/server4:/var/lib/neo4j/import
      #- ./metrics/server4:/var/lib/neo4j/metrics
      #- ./licenses/server4:/var/lib/neo4j/licenses
      #- ./ssl/server4:/var/lib/neo4j/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/fedeymanu
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=SECONDARY
      - NEO4J_dbms.memory.transaction.total.max=3G
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}